In [2]:
import h5py
import json

# How much space?
All layers: 31.9 GB
Just the top: 2.9GB

In [47]:
l = ['▁', '"', '▁Mr', '.', '▁Allen', '▁objected', '▁to', '▁this', '▁analogy', '▁because', '▁it', '▁seems', '▁to', '▁', '"', '▁assimilate', '▁the', '▁status', '▁of', '▁blacks', '▁to', '▁that', '▁of', '▁animals', '▁', '-', '-', '▁as', '▁a', '▁mere', '▁project', '▁of', '▁charity', '▁', ',', '▁of', '▁human', 'e', 'ness', '▁', '.', '▁', '”']

In [52]:
ord(l[0])

9601

In [48]:
len(l)

43

In [53]:
len([s for s in l if s.find(chr(9601))>=0])

33

In [17]:
n_sent = 131611
bytes_per_num = 4

In [21]:
# Set `n_layer_d`, `n_neuron_d`, `h5_d`
network_l = [
    '/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/bert_large_cased/ptb_pos_dev.hdf5',
    '/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/openai_transformer/ptb_pos_dev.hdf5',
    '/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/bert_base_cased/ptb_pos_dev.hdf5',
    '/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/elmo_original/ptb_pos_dev.hdf5',
    '/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/calypso_transformer_6_512_base/ptb_pos_dev.hdf5',
    '/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/elmo_4x4096_512/ptb_pos_dev.hdf5',  
    '/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/xlnet_large_cased/ptb_pos_dev.hdf5',   
    '/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/gpt2_small/ptb_pos_dev.hdf5',
    '/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/xlm-mlm-enro-1024/ptb_pos_dev.hdf5',
    '/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/xlm-mlm-enfr-1024/ptb_pos_dev.hdf5',
    '/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/gpt2_medium/ptb_pos_dev.hdf5',
    '/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/xlm-mlm-en-2048/ptb_pos_dev.hdf5',
    '/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/xlm-clm-ende-1024/ptb_pos_dev.hdf5',
    '/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/xlnet_base_cased/ptb_pos_dev.hdf5',
    '/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/xlm-mlm-ende-1024/ptb_pos_dev.hdf5',
    '/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/xlm-clm-enfr-1024/ptb_pos_dev.hdf5',
]

n_layer_d = {}
n_neuron_d = {}
h5_d = {}
for network in network_l:
    h5_d[network] = h5py.File(network)
    n_layer_d[network] = h5_d[network]['0'].shape[0]
    n_neuron_d[network] = h5_d[network]['0'].shape[2]

In [43]:
# find first sentence with diff tokenization
for i in range(5512):
    bert = network_l[0]
    correct_length = h5_d[bert][str(i)].shape[1]
    
    for network in network_l:
        l = h5_d[network][str(i)].shape[1]
        if l > correct_length+1:
            print(i, network)
            break
    else:
        continue
    break

1 /data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/xlm-mlm-enro-1024/ptb_pos_dev.hdf5


In [45]:
# find number of different tokenizations
count = 0
for i in range(5512):
    bert = network_l[0]
    correct_length = h5_d[bert][str(i)].shape[1]
    
    for network in network_l:
        l = h5_d[network][str(i)].shape[1]
        if l > correct_length:
            count += 1
            break

In [46]:
count

4039

In [44]:
for network in network_l:
    print(network, h5_d[network]['1'].shape)

/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/bert_large_cased/ptb_pos_dev.hdf5 (25, 33, 1024)
/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/openai_transformer/ptb_pos_dev.hdf5 (13, 33, 768)
/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/bert_base_cased/ptb_pos_dev.hdf5 (13, 33, 768)
/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/elmo_original/ptb_pos_dev.hdf5 (3, 33, 1024)
/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/calypso_transformer_6_512_base/ptb_pos_dev.hdf5 (7, 33, 1024)
/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/elmo_4x4096_512/ptb_pos_dev.hdf5 (5, 33, 1024)
/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/xlnet_large_cased/ptb_pos_dev.hdf5 (24, 33, 1024)
/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/gpt2_small/ptb_pos_dev.hdf5 (12, 33, 768)
/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/xlm-mlm-enro-1024/ptb_p

In [42]:
net1 = network_l[0] # bert large
net2 = network_l[8] # xlm enro

json1 = json.loads(h5_d[net1]['sentence_to_index'][0])
json2 = json.loads(h5_d[net2]['sentence_to_index'][0])

json1 == json2

True

In [11]:
n_layer_d

{'/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/bert_large_cased/ptb_pos_dev.hdf5': 25,
 '/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/openai_transformer/ptb_pos_dev.hdf5': 13,
 '/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/bert_base_cased/ptb_pos_dev.hdf5': 13,
 '/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/elmo_original/ptb_pos_dev.hdf5': 3,
 '/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/calypso_transformer_6_512_base/ptb_pos_dev.hdf5': 7,
 '/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/elmo_4x4096_512/ptb_pos_dev.hdf5': 5,
 '/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/xlnet_large_cased/ptb_pos_dev.hdf5': 24,
 '/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/gpt2_small/ptb_pos_dev.hdf5': 12,
 '/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/xlm-mlm-enro-1024/ptb_pos_dev.hdf5': 6,
 '/data/sls/temp/belinkov/contextu

In [12]:
n_neuron_d

{'/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/bert_large_cased/ptb_pos_dev.hdf5': 1024,
 '/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/openai_transformer/ptb_pos_dev.hdf5': 768,
 '/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/bert_base_cased/ptb_pos_dev.hdf5': 768,
 '/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/elmo_original/ptb_pos_dev.hdf5': 1024,
 '/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/calypso_transformer_6_512_base/ptb_pos_dev.hdf5': 1024,
 '/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/elmo_4x4096_512/ptb_pos_dev.hdf5': 1024,
 '/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/xlnet_large_cased/ptb_pos_dev.hdf5': 1024,
 '/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/gpt2_small/ptb_pos_dev.hdf5': 768,
 '/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/xlm-mlm-enro-1024/ptb_pos_dev.hdf5': 1024,
 '/data/sls/tem

In [13]:
total = 0
for n_layer, n_neuron in zip(n_layer_d.values(), n_neuron_d.values()):
    total += n_layer * n_neuron * n_sent * bytes_per_num
total

96764618752

In [14]:
# just the top
total = 0
for n_layer, n_neuron in zip(n_layer_d.values(), n_neuron_d.values()):
    total += n_neuron * n_sent * bytes_per_num
total

8625258496

In [15]:
# What's the size of the loop
sum(n_layer_d.values())

180

# Are the tests successful?

In [1]:
import pickle

In [2]:
method_l = [
    "maxcorr",
    "mincorr",
    "maxlinreg", 
    "minlinreg",
    "cca",
    "lincka",
    # "rbfcka",
]

fname_d = {method: "/data/sls/temp/johnmwu/contextual-corr-analysis/results_test_{0}".format(method) 
           for method in method_l}

In [3]:
for method in method_l:
    fname = fname_d[method]
    f = open(fname, "rb")
    data = pickle.load(f)
    
    print("\n\n" + method)
    print(data.keys())



maxcorr
dict_keys(['corrs', 'pairs', 'similarities', 'neuron_sort', 'neuron_notated_sort'])


mincorr
dict_keys(['corrs', 'pairs', 'similarities', 'neuron_sort', 'neuron_notated_sort'])


maxlinreg
dict_keys(['pred_power', 'similarities', 'neuron_sort', 'neuron_notated_sort'])


minlinreg
dict_keys(['pred_power', 'similarities', 'neuron_sort', 'neuron_notated_sort'])


cca
dict_keys(['corrs', 'sv_similarities', 'pw_alignments', 'pw_corrs', 'pw_similarities'])


lincka
dict_keys(['similarities'])


In [7]:
f = open(fname_d["maxcorr"], 'rb')
data = pickle.load(f)
data['corrs']

{'elmo_original_0': {'elmo_original_1': array([0.2644712 , 0.24154745, 0.3417127 , ..., 0.14911196, 0.3287669 ,
         0.1628318 ], dtype=float32),
  'elmo_original_2': array([0.2790686 , 0.17504421, 0.2784313 , ..., 0.14538047, 0.22215934,
         0.15905769], dtype=float32)},
 'elmo_original_1': {'elmo_original_0': array([0.29818842, 0.19084944, 0.17174841, ..., 0.17371958, 0.151198  ,
         0.14904524], dtype=float32),
  'elmo_original_2': array([0.6606671 , 0.6367155 , 0.54827076, ..., 0.7002142 , 0.6624288 ,
         0.6925493 ], dtype=float32)},
 'elmo_original_2': {'elmo_original_0': array([0.16851643, 0.12632947, 0.22938968, ..., 0.19309205, 0.13923243,
         0.17923273], dtype=float32),
  'elmo_original_1': array([0.6606671 , 0.6367155 , 0.54827076, ..., 0.7002142 , 0.6624288 ,
         0.6925493 ], dtype=float32)}}

# What do the attn files look like?
- They're structured the same way as the activations files
- Each tensor is 4D, with axes (num_layers, num_heads, next_layer_ix, prev_layer_ix)
- The values in the tensors are the values in

$$
\mathrm{softmax}(Q^TV)
$$

In [4]:
import h5py
import json
import numpy as np

In [5]:
# param
fname = "/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/bert_base_cased/ptb_pos_dev_attn.hdf5"

In [6]:
h5 = h5py.File(fname, 'r')
sentence_d = json.loads(h5['sentence_to_index'][0])
temp = {} # TO DO: Make this more elegant?
for k, v in sentence_d.items():
    temp[v] = k
sentence_d = temp # {str ix, sentence}
indices = list(sentence_d.keys())

In [7]:
# Order of axes
for i in range(10):
    ix = str(i)
    sent = sentence_d[ix]
    attn = h5[ix]
    
    print("Sentence length: {0}".format(len(sent.split())))
    print("Shape: {0}".format(attn.shape))
    print()

Sentence length: 8
Shape: (12, 12, 8, 8)

Sentence length: 33
Shape: (12, 12, 33, 33)

Sentence length: 28
Shape: (12, 12, 28, 28)

Sentence length: 21
Shape: (12, 12, 21, 21)

Sentence length: 19
Shape: (12, 12, 19, 19)

Sentence length: 7
Shape: (12, 12, 7, 7)

Sentence length: 24
Shape: (12, 12, 24, 24)

Sentence length: 22
Shape: (12, 12, 22, 22)

Sentence length: 27
Shape: (12, 12, 27, 27)

Sentence length: 23
Shape: (12, 12, 23, 23)



In [19]:
# What exactly is contained? Also, order of last two axes
attn_ar = np.array(h5['3405'])
a = attn_ar[0, 0, :, :]
a.sum(axis=1)

array([1.        , 0.99999994], dtype=float32)

In [22]:
for a in np.array(h5['3496'])[3]:
    print(a)

[[0.90824974 0.0917503 ]
 [0.9087661  0.09123389]]
[[0.9450725  0.05492758]
 [0.98557544 0.01442447]]
[[0.93533957 0.06466043]
 [0.9872321  0.0127679 ]]
[[0.7961024  0.20389754]
 [0.93405366 0.06594636]]
[[0.8841361  0.11586393]
 [0.8325231  0.16747688]]
[[0.9540099  0.04599005]
 [0.8944529  0.105547  ]]
[[0.95842683 0.04157317]
 [0.92747676 0.07252326]]
[[0.9772744  0.02272559]
 [0.23067053 0.7693294 ]]
[[0.8956895  0.10431045]
 [0.98439395 0.01560605]]
[[0.62169164 0.37830836]
 [0.5389814  0.46101865]]
[[0.8585013  0.14149868]
 [0.69356483 0.3064352 ]]
[[9.9905354e-01 9.4647484e-04]
 [9.8925859e-01 1.0741444e-02]]


In [18]:
a

array([[0.56150335, 0.43849668],
       [0.64035594, 0.35964406]], dtype=float32)

# xlnet wanted sizes are zero?

In [3]:
import h5py
import json
import numpy as np

In [1]:
fname = "/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/xlnet_base_cased/ptb_pos_dev_mnli.hdf5"

In [4]:
h5 = h5py.File(fname, 'r')
sentence_d = json.loads(h5['sentence_to_index'][0])
temp = {} # TO DO: Make this more elegant?
for k, v in sentence_d.items():
    temp[v] = k
sentence_d = temp # {str ix, sentence}
indices = list(sentence_d.keys())

In [23]:
h5['0'][11][:, 0:5]

array([[-0.2408489 , -0.800417  , -0.05489704, -0.20166916, -0.53048587],
       [-0.24084893, -0.8004171 , -0.05489708, -0.20166902, -0.53048587],
       [-0.24084893, -0.8004171 , -0.05489707, -0.201669  , -0.53048587],
       [-0.24084893, -0.8004171 , -0.05489706, -0.2016691 , -0.53048587],
       [-0.2408489 , -0.8004171 , -0.05489706, -0.2016691 , -0.53048587],
       [-0.2408489 , -0.8004171 , -0.05489706, -0.20166911, -0.53048575],
       [-0.2408489 , -0.800417  , -0.05489706, -0.20166916, -0.53048587],
       [-0.24084884, -0.8004171 , -0.05489708, -0.2016691 , -0.53048575]],
      dtype=float32)

In [22]:
h5['1'][11][:, 0:5]

array([[-0.24084891, -0.8004172 , -0.05489706, -0.20166914, -0.53048587],
       [-0.2408489 , -0.8004173 , -0.05489706, -0.20166911, -0.53048587],
       [-0.24084893, -0.8004172 , -0.05489708, -0.20166916, -0.53048587],
       [-0.24084893, -0.8004173 , -0.05489706, -0.20166919, -0.53048587],
       [-0.24084891, -0.8004172 , -0.05489707, -0.20166917, -0.5304858 ],
       [-0.2408489 , -0.8004172 , -0.05489707, -0.2016692 , -0.53048587],
       [-0.24084891, -0.8004173 , -0.05489706, -0.2016691 , -0.53048587],
       [-0.24084893, -0.8004172 , -0.05489706, -0.20166913, -0.5304858 ],
       [-0.24084891, -0.8004172 , -0.05489706, -0.20166916, -0.53048587],
       [-0.24084893, -0.8004172 , -0.054897  , -0.20166913, -0.53048587],
       [-0.24084893, -0.8004172 , -0.05489706, -0.20166916, -0.53048587],
       [-0.2408489 , -0.8004172 , -0.05489708, -0.20166911, -0.53048587],
       [-0.24084891, -0.8004171 , -0.05489706, -0.20166916, -0.5304858 ],
       [-0.2408489 , -0.8004172 , -0.0

In [8]:
h5['1']

<HDF5 dataset "1": shape (12, 33, 768), type "<f4">

# Why is PearsonMaxMinCorr2 getting infs and NaNs?

In [2]:
import h5py
import numpy as np
import torch

In [2]:
# param
fname = "/data/sls/temp/belinkov/contextual-corr-analysis/contextualizers/bert_base_cased/ptb_pos_dev_attn.hdf5"

In [18]:
# an offending pair, according to the output
idx = '3405'
l1, l2 = 3, 10

In [19]:
h5 = h5py.File(fname, 'r')

In [20]:
t1 = torch.FloatTensor(h5[idx][l1])
t2 = torch.FloatTensor(h5[idx][l2])

In [21]:
t11, t12, t13 = t1.size()
t21, t22, t23 = t2.size()
t1 = t1.reshape(t11, 1, t12, t13)
t2 = t2.reshape(1, t21, t22, t23)

In [22]:
nz = (t1!=0) & (t2!=0) # "nonzero"
n = nz.sum(dim=-1).float() # n = length to use
x1, x2 = t1.sum(dim=-1), t2.sum(dim=-1)
x11, x12, x22 = (t1*t1).sum(dim=-1), (t1*t2).sum(dim=-1), (t2*t2).sum(dim=-1)
num = x12-(x1*x2/n)
denom = torch.sqrt((x11-(x1*x1/n)) * (x22-(x2*x2/n)))
corr = num/denom

In [30]:
(x11-(x1*x1/n))

tensor([[[0.3480, 0.3697],
         [0.3480, 0.3697],
         [0.3480, 0.3697],
         [0.3480, 0.3697],
         [0.3480, 0.3697],
         [0.3480, 0.3697],
         [0.3480, 0.3697],
         [0.3480, 0.3697],
         [0.3480, 0.3697],
         [0.3480, 0.3697],
         [0.3480, 0.3697],
         [0.3480, 0.3697]],

        [[0.4282, 0.4898],
         [0.4282, 0.4898],
         [0.4282, 0.4898],
         [0.4282, 0.4898],
         [0.4282, 0.4898],
         [0.4282, 0.4898],
         [0.4282, 0.4898],
         [0.4282, 0.4898],
         [0.4282, 0.4898],
         [0.4282, 0.4898],
         [0.4282, 0.4898],
         [0.4282, 0.4898]],

        [[0.2975, 0.3844],
         [0.2975, 0.3844],
         [0.2975, 0.3844],
         [0.2975, 0.3844],
         [0.2975, 0.3844],
         [0.2975, 0.3844],
         [0.2975, 0.3844],
         [0.2975, 0.3844],
         [0.2975, 0.3844],
         [0.2975, 0.3844],
         [0.2975, 0.3844],
         [0.2975, 0.3844]],

        [[0.2391, 0.23

In [24]:
corr

tensor([[[ 1.0000,  1.0000],
         [ 1.0000,  1.0000],
         [ 1.0000,  1.0000],
         [ 1.0000,  1.0000],
         [ 1.0000,  1.0000],
         [ 1.0000,  1.0000],
         [ 1.0000,  1.0000],
         [ 1.0000,  1.0000],
         [ 1.0000,  1.0000],
         [ 1.0000,  1.0000],
         [ 1.0000,  1.0000],
         [ 1.0000,  1.0000]],

        [[ 1.0000,  1.0000],
         [ 1.0000,  1.0000],
         [ 1.0000,  1.0000],
         [ 1.0000,  1.0000],
         [ 1.0000,  1.0000],
         [ 1.0000,  1.0000],
         [ 1.0000,  1.0000],
         [ 1.0000,  1.0000],
         [ 1.0000,  1.0000],
         [ 1.0000,  1.0000],
         [ 1.0000,  1.0000],
         [ 1.0000,  1.0000]],

        [[ 1.0000,  1.0000],
         [ 1.0000,  1.0000],
         [ 1.0000,  1.0000],
         [ 1.0000,  1.0000],
         [ 1.0000,  1.0000],
         [ 1.0000,  1.0000],
         [ 1.0000,  1.0000],
         [ 1.0000,  1.0000],
         [ 1.0000,  1.0000],
         [ 1.0000,  1.0000],
         [

In [ ]:
torch.tensor(1)/torch.tensor(0) # this kills the kernel..

In [6]:
torch.FloatTensor([1]) / torch.FloatTensor([0])

tensor([inf])